let e = { 
		opacity: 0.9, 
		backgroundColor: "#FFFFFF", 
		color: "#333333", 
		strokeWidth: 10, 
		timeOnScreen: 100, 
		loadingAnimationSpeed: "1s", 
		loadingAnimationTimingFunction: "linear", 
		loadingAnimationIterationCount: "infinite", 
		loadingText: "Loading...", 
		loadingTextSize: "32px",
	},
  t = document.querySelector("*"),
  r = document.createElement("style"),
  i = document.createElement("div"),
  zt = document.createElement("span"),
  s = "http://www.w3.org/2000/svg",
  n = document.createElementNS(s, "svg"),
  o = document.createElementNS(s, "circle");

document.head.appendChild(r),
  (r.innerHTML = "@keyframes swell{from { transform: rotate(0deg); }to{transform:rotate(360deg)}}"),
  i.setAttribute("style", "opacity: "+ e.opacity +";background-color:" + e.backgroundColor + ";color:" + e.backgroundColor + ";display:flex;align-items:center;justify-content:center;position:fixed;top:0;height:100vh;width:100vw;z-index:2147483647"),
  document.body.setAttribute("style", "overflow:hidden!important;"),
  document.body.prepend(i),
  n.setAttribute("style", "height:50px;color:"+ e.color +";animation:"+ e.loadingAnimationSpeed +" swell "+ e.loadingAnimationTimingFunction +" "+ e.loadingAnimationIterationCount),
  n.setAttribute("viewBox", "0 0 100 100"),
  i.prepend(n),
  o.setAttribute("cx", "50"),
  o.setAttribute("cy", "50"),
  o.setAttribute("r", "35"),
  o.setAttribute("fill", "none"),
  o.setAttribute("stroke", "currentColor"),
  o.setAttribute("stroke-dasharray", "165 57"),
  o.setAttribute("stroke-width", e.strokeWidth),
  n.prepend(o),
  zt.setAttribute("style", "font-size: "+ e.loadingTextSize +";color:"+ e.color +";margin-left:5px;"),
  zt.textContent = e.loadingText,
  n.insertAdjacentElement('afterend', zt),
  (t.style.pointerEvents = "none"),
  (t.style.userSelect = "none"),
  (t.style.cursor = "wait"),
  (window.onload = () => {
    setTimeout(() => {
      (t.style.pointerEvents = ""), (t.style.userSelect = ""), (t.style.cursor = ""), i.remove(), document.body.setAttribute("style", "");
    }, e.timeOnScreen);
  });
